#ifndef SPA_TEAM35_CODE35_SRC_SPA_SRC_DESIGNEXTRACTOR_RELATIONSHIPEXTRACTOR_H_
#define SPA_TEAM35_CODE35_SRC_SPA_SRC_DESIGNEXTRACTOR_RELATIONSHIPEXTRACTOR_H_

class PrecomputableRelationshipExtractor {
public:
    virtual void precomputeRelationship() = 0;
};

#endif //SPA_TEAM35_CODE35_SRC_SPA_SRC_DESIGNEXTRACTOR_RELATIONSHIPEXTRACTOR_H_
