name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    BUILD_TYPE: Release

jobs:
  build_windows:
    runs-on: windows-latest
    timeout-minutes: 3
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        shell: bash
        run: |
          cd Team35/Code35
          mkdir build
          cd build
          cmake -A Win32 ..
          cmake --build . --target unit_testing --config Release
          cmake --build . --target integration_testing --config Release
          cmake --build . --target autotester --config Release
          cd ../..
          
  build_macos:
    runs-on: macos-latest
    timeout-minutes: 3
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team35/Code35/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
